apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog
spec:
  replicas: 20
  selector:
    matchLabels:
      app: memory-hog
  template:
    metadata:
      labels:
        app: memory-hog
    spec:
      containers:
      - name: memory-consumer
        image: progrium/stress
        args: ["--vm", "1", "--vm-bytes", "800M", "--timeout", "600s"]
        resources:
          requests:
            memory: 800Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 200m
